language: python
python:
- 2.7
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
  global:
  - secure: DhwcuTr4dpMdAbaNT/u5AjqYLEDwOeCZiGOPMgkunIra7KdGbs05Zqyx+XRbPsqIaoECLjQqv940Yq5tJqJBbwSBYskzyKJuks69CYvPVMWj2hCOD4NGOV4iea/dQ/89dlaiytoDK43+R4t0xiFhwkIqUEZi8Sc9UJVV0B2sJ1+EKL2tA9I2YOb6JkPFeN61qCj4YV3FX9ux1+LBm7Lmd9bAdY1uncOV82Iyx/s6yqub3AUygktvAzAPXkS5cWHBpPM+NTRjWgeo5rihGA3HkBtr9elLHN6zai+xTOrHNBkLhYiLlEnhS9VaegL9sZ7Sst5vf4Aj6CxqWBWDUNIsAR/UEy+ECSmU6byprNsTmWvN87ZH3R5RN6BDQZ6FKBjbHj2+quHCT/P6y3Gda7g1+73ZdWTnbygcjKWqtdhs39wsVA+hw0Twg3Gc8Ce+zPXa0grSvmxsHPoQ7pcdZmMIgcbBoWwCgNNSOCEdFsdMJc8ebz/0WsMsZMijvJbCSwMeWzK/uv9mtR52wK3qwiTvdRA9ibJV+1vgUrIPTvFgF/9qFsa0SpWAJ6Y9Rfcv7MyB4nH5vdg3RPyLpGzLB36T3SMsWR3eokBnkKwlvGxx7gHLp2IfY06OtlZucAsKTgOjdz0RTNHcmp72Fgjvl4I3qfjKPZiOuAqeaKfGQzW7z/Y=
  - secure: Nht5CLDYughnjO0BoZ2iAS+HfrKHl7d1Hv3aR+yLM4FBhufc2bmJp5wzBUM8Hsd25rv+GD32aLaYk5p8vGr63UjJlTY2+9P535iHh9aZDfFpRL6mxks2GQj0tI1S/UjFoLro6mJpGPrmurqzPfiHxugTNeSYX+hu5w7qE5T30Qxq0NbvYuGnNcWbUOZ1JMNJ6MoFDcapcTN5b7VpkcJqh6llyjNxsbR93tXgnUy+xgb43hQ9BaES8hhWcAbhXMQqSb0j7WM4ZbvG9D2PYax9WnVwCfkRXK67pMF3iw4/ZqwNvhXJ0++w3jUmGHQjIYFlcfomo90sKqAx6qyhjFusNyG2gKvgpb3yzbN7ZqzcXKczQZKARy0SxHKGIOggo8Sq0YPfthyxMkqCIyNIdRGjCiHjj+e033jnwLLpPJYmBEnSz6tUg2fzNg69LrKF33f9w0jK20fpxPYntVKOhp8BcvT2Y424hQyi1z9COXRotnGLo3Qd6TQsq2eEnDGdy0FpgL6sLHp5x6mB9lCRnXkZHob4hoUekhM/4aKsVvyq5I86PNXCeDYtBrxDTnrVCGv78mM+TQmFo0JJU5JlCiqxoxXHGyNA+98coZZLnnSNUuzWd6FokkujXQ6Htb3KfIdZz1e0o4HR/u2uwSsCBUDjykPD8+mqoGR8oCMFe2Y/UE8=
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose --upgrade
- docker-compose --version
install:
- cd v01
- docker-compose -f docker-compose-build.yml up -d --build
- docker-compose -f docker-compose-build.yml ps
- docker cp configs/akeneo/parameters_test.yml akeneo:/home/akeneo/app/config/parameters.yml
- bash init.sh
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
after_success:
- cd v3_0
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker-compose -f docker-compose-build.yml images
- docker push trydirect/akeneo:3.0
