version: '2.1'

services:
  bitrix:
    image: trydirect/bitrix1c:standard
    container_name: bitrix
    build: build/standard
    ports:
      - 80:80
    volumes:
       - ./configs/apache/bitrix.conf:/etc/apache2/sites-enabled/000-default.conf
#      - ./configs/bitrix:/var/www/html
    restart: always
#    entrypoint: bash -c "sleep infinity;"
#    entrypoint: "supervisord -c /etc/supervisor/supervisord.conf -n "
    ulimits:
      stack: -1
    links:
      - db
    env_file:
      - .env

  db:
    image: mysql:5.7
    container_name: bitrix_db
    env_file:
      - .env
#    volumes:
#      - ./configs/mysql:/etc/mysql/conf.d/
